# Generated by Django 6.0.4 on 2026-04-22 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='conversacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.conversacion', verbose_name='Conversacion'),
        ),
    ]
